name: Deploy frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t dockwall/vite-react-docker-test -f Dockerfile.dev .
      - run: docker run -e CI=true dockwall/vite-react-docker-test npm run test
